### ISSUE TITLE
近两天很容易出现登录失败

### ISSUE THREAD

**Issue by zhuwenbing** [wes-lin/Cloud189Checkin#11]
失败信息如下：
```
登录失败:{"errno":-104,"code":"ECONNRESET","syscall":"read"}
```
可否优化下，谢谢！

**Comment by wes-lin** [comment]
可能是网络问题吧，这几天再观察下，如果是天翼的问题话，我这边也没法解决，只能一天再多跑一次重试了。

**Comment by zhuwenbing** [comment]
目前已经稳定了，感谢回复！
另外想表达的是可否通过天翼接口返回的状态码，比如说这个errno来确定要不要再执行一遍？
没有问题了，这个issue先关了，再次感谢！

**Comment by wes-lin** [comment]
你的建议很好，本来就想简单写个简易的脚本，很多异常情况就没去处理，后期如果经常会出现网络问题，会考虑重构下代码。
