### ISSUE TITLE
请问server酱怎么不推送呢

### ISSUE THREAD

**Issue by 2557558162** [wes-lin/Cloud189Checkin#15]
rt 我已经配置好了server酱 服务器测试也能发送接受成功 但是这个项目填写之后还是收不到。
要开启什么吗

**Comment by wes-lin** [comment]
你有在环境变量那边配置好SENKEY吗？我的截图你可以参考下

**Comment by 2557558162** [comment]
有的 都配置好了  https://pic.imgdb.cn/item/64ba03521ddac507cc96e6e2.png 如图 还需要设置什么吗

**Comment by wes-lin** [comment]
每天执行任务有出现错误吗？可以发下你server酱那边的配置吗？

**Comment by borisxxz** [comment]
根据截图可以发现，作者写文本时犯了个错误，示例截图和配置表里的变量都是“SENDKEY”，而文本的是“SENKEY”，少了字母“D”。因此通过复制粘贴而填写的变量名称会无法识别，也就不可能发送了

**Comment by wes-lin** [comment]
> 根据截图可以发现，作者写文本时犯了个错误，示例截图和配置表里的变量都是“SENDKEY”，而文本的是“SENKEY”，少了字母“D”。因此通过复制粘贴而填写的变量名称会无法识别，也就不可能发送了

确实是，谢谢指正，后续改下文本。
