### ISSUE TITLE
是否有计划添加自定义端口？

### ISSUE THREAD

**Issue by borisxxz** [wes-lin/Cloud189Checkin#16]
Servers酱低频使用一下还行，但量多一点就要付费了。不过他有个开源计划能通过云函数搭建。但网址会发生变化，因此能不能把发送过程独立出来以支持修改呢？

**Comment by wes-lin** [comment]
你的意思可以支持配置server酱发送的服务器地址是吗？

**Comment by borisxxz** [comment]
除此以外，真的非常感谢！我没想到真的会收到回复，现在网盘换签到方式以后已经没几个能用的了，我真的期望你能一直保持更新（能用就怒刷版本号（doge）

**Comment by borisxxz** [comment]
是的，不过我觉得没必要单独做扩展。因为我没在程序里找到server酱对应的url，所以我才说“把发送过程独立出来以支持修改”。但如果使用的是GET或者是POST请求，那把server酱前边那串固定的网址用变量进行替换，然后把它放到config里边应该就够用了（只要前边那串固定的网址找得到，或者是知道怎么发送请求的，应该就可以让使用者自己修改了，没必要自己去做扩展）。
