### ISSUE TITLE
请问下任务链接是怎么确定的呀，我想试着把其他平台的签到也集成进来

### ISSUE THREAD

**Issue by yiwp9** [wes-lin/Cloud189Checkin#19]
![1693308400110](https://github.com/wes-lin/Cloud189Checkin/assets/30064590/9deca9c7-020d-4e3a-b823-78c3c33335ff)
就是这些任务的链接

**Comment by wes-lin** [comment]
这个是分析网页的请求，不过我这个也是参考别人的。你说的别的平台是指189云盘之外的吗？这个脚本应该不实用。

**Comment by yiwp9** [comment]
感谢回复，我的意思确实是除 天翼云盘 之外的平台。不适用的话我再去找找其他的。
