### ISSUE TITLE
图形验证码错误怎么搞

### ISSUE THREAD

**Issue by STC214** [wes-lin/Cloud189Checkin#21]

**Comment by wes-lin** [comment]
确认下你的账号密码是否设置对了

**Comment by Lin-cc** [comment]
我也出现了图形验证码错误，检查发现新建ENV的时候命名是随便命的，执行的时候是指定读取ENV名字为user的环境，所以把action里面配置的环境名跟自己建的名字统一一下就可以正常运行了。
