### ISSUE TITLE
需要图片验证吗怎么破？

### ISSUE THREAD

**Issue by GongYanYu** [wes-lin/Cloud189Checkin#33]
![image](https://github.com/wes-lin/Cloud189Checkin/assets/43344004/e6ded157-1b02-4b42-88bc-e335e28686b6)

**Comment by wes-lin** [comment]
> ![image](https://github.com/wes-lin/Cloud189Checkin/assets/43344004/e6ded157-1b02-4b42-88bc-e335e28686b6)
> 

一般是你的账号密码没有配置好，请检查下。
