### ISSUE TITLE
只能完成第1次抽奖，后面两次没有获得空间

### ISSUE THREAD

**Issue by BT603** [wes-lin/Cloud189Checkin#37]
_**两个账号都是这样**_

签到获得63M空间
第1次抽奖成功,抽奖获得天翼云盘50M空间
第2次抽奖成功,抽奖获得undefined
第3次抽奖成功,抽奖获得undefined
任务执行完毕

**Comment by hugcabbage** [comment]
> _**两个账号都是这样**_
> 
> 签到获得63M空间 第1次抽奖成功,抽奖获得天翼云盘50M空间 第2次抽奖成功,抽奖获得undefined 第3次抽奖成功,抽奖获得undefined 任务执行完毕

因为返回了RequestFrequent，设置延迟即可

**Comment by ChangJun1** [comment]
> > _**两个账号都是这样**_
> > 签到获得63M空间 第1次抽奖成功,抽奖获得天翼云盘50M空间 第2次抽奖成功,抽奖获得undefined 第3次抽奖成功,抽奖获得undefined 任务执行完毕
> 
> 因为返回了RequestFrequent，设置延迟即可

遇到了同样的问题。请问是在app.js中的dotask函数里的for循环里面添加延迟吗

**Comment by hugcabbage** [comment]
> > > _**两个账号都是这样**_
> > > 签到获得63M空间 第1次抽奖成功,抽奖获得天翼云盘50M空间 第2次抽奖成功,抽奖获得undefined 第3次抽奖成功,抽奖获得undefined 任务执行完毕
> > 
> > 
> > 因为返回了RequestFrequent，设置延迟即可
> 
> 遇到了同样的问题。请问是在app.js中的dotask函数里的for循环里面添加延迟吗

是的

**Comment by hugcabbage** [comment]
> > > _**两个账号都是这样**_
> > 
> > 
> > > 
> > 
> > 
> > > 签到获得63M空间 第1次抽奖成功,抽奖获得天翼云盘50M空间 第2次抽奖成功,抽奖获得undefined 第3次抽奖成功,抽奖获得undefined 任务执行完毕
> > 
> > 
> > 因为返回了RequestFrequent，设置延迟即可
> 
> 我也遇到了，在哪里改啊，谢谢。

https://github.com/hugcabbage/Cloud189Checkin/commit/5915bf3272a34e8222c06f607513b8c06646e53c

**Comment by wes-lin** [comment]
> > _**两个账号都是这样**_
> > 签到获得63M空间 第1次抽奖成功,抽奖获得天翼云盘50M空间 第2次抽奖成功,抽奖获得undefined 第3次抽奖成功,抽奖获得undefined 任务执行完毕
> 
> 因为返回了RequestFrequent，设置延迟即可

欢迎提PR
