### ISSUE TITLE
大神，有没有办法签两个号？

### ISSUE THREAD

**Issue by yangrusen** [wes-lin/Cloud189Checkin#4]
我没有编程基础，只能照葫芦画瓢，还望多多指教，谢谢！

**Comment by wes-lin** [comment]
暂时没有计划弄，不过比较笨的一个办法就是你再fork这个仓库，改个另外一个名字，然后再配另外的账号信息就行了。

**Comment by wes-lin** [comment]
已支持，根据提示操作
