### ISSUE TITLE
天翼云盘tv版签到也能领取奖励，不添加呢

### ISSUE THREAD

**Issue by hualuoshuijia** [wes-lin/Cloud189Checkin#43]
天翼云盘tv版签到也能领取奖励，不添加呢

**Comment by wes-lin** [comment]
请问你找到具体的api请求吗？我可以集成看看

**Comment by hualuoshuijia** [comment]
这我不懂了，我不是学编码的，只知道tv版也有签到

**Comment by wes-lin** [comment]
> > 请问你找到具体的api请求吗？我可以集成看看
> 
> https://npmmirror.com/package/@asunajs/dist/files/ecloud.ql.js?version=0.0.13
> 
> 这个里面有TV版签到功能，不知道有没有用
我大概了看了这个的源码，和我现在的签到功能其实是完全一样的，不知道你提到TV版签到是不是家庭空间的，这个我最近的代码里也都是有的。
