### ISSUE TITLE
第三次抽奖为无效抽奖

### ISSUE THREAD

**Issue by catlair** [wes-lin/Cloud189Checkin#44]
不管是接口表现，还是 https://m.cloud.189.cn/zhuanti/2016/sign/myPrizeList.jsp 的记录，第三次（TASK_2022_FLDFS_KJ）抽奖看似都是有效的。

https://[cloud.189.cn/api/portal/getUserSizeInfo.action?noCache=0.4256780630597663](https://cloud.189.cn/api/portal/getUserSizeInfo.action?noCache=0.4256780630597663)

https://[cloud.189.cn/api/portal/listGrow.action?noCache=0.5555609671834492](https://cloud.189.cn/api/portal/listGrow.action?noCache=0.5555609671834492)

但是从这两个接口都无法看到第三次增加的记录以及实际空间的变化

**Comment by versionJun** [comment]
好像 第二次（TASK_SIGNIN_PHOTOS）抽奖也无效了

**Comment by catlair** [comment]
> 好像 第二次（TASK_SIGNIN_PHOTOS）抽奖也无效了

没有啊，刚试了正常的

**Comment by versionJun** [comment]
> > 好像 第二次（TASK_SIGNIN_PHOTOS）抽奖也无效了
> 
> 没有啊，刚试了正常的
还是失败哦 返回结果为
{ errorCode: 'RequestFrequent', errorMsg: 'RequestFrequent' }

**Comment by versionJun** [comment]
> > 好像 第二次（TASK_SIGNIN_PHOTOS）抽奖也无效了
> 
> 没有啊，刚试了正常的

还是失败 返回结果为
{ errorCode: 'RequestFrequent', errorMsg: 'RequestFrequent' }

**Comment by wes-lin** [comment]
> > > 好像 第二次（TASK_SIGNIN_PHOTOS）抽奖也无效了
> > 
> > 没有啊，刚试了正常的
> 
> 还是失败 返回结果为
> { errorCode: 'RequestFrequent', errorMsg: 'RequestFrequent' }
> 

你的代码是最新的吗，这个问题最近已经处理了

**Comment by versionJun** [comment]
> > > > 好像 第二次（TASK_SIGNIN_PHOTOS）抽奖也无效了
> > > 
> > > 
> > > 没有啊，刚试了正常的
> > 
> > 
> > 还是失败 返回结果为
> > { errorCode: 'RequestFrequent', errorMsg: 'RequestFrequent' }
> 
> 你的代码是最新的吗，这个问题最近已经处理了

感谢 已解决 发现是调用频繁 未添加延迟触发

**Comment by wes-lin** [comment]
去除无用三次抽奖
