### ISSUE TITLE
运行错误提示Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by echs-top** [wes-lin/Cloud189Checkin#48]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, nick-fields/retry@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by echs-top** [comment]
好像是，不过这几天好像没报错

**Comment by echs-top** [comment]
我是直接在github运行的

**Comment by wes-lin** [comment]
可能是github的问题，后续我会升级下node依赖
