### ISSUE TITLE
不行了 快更新啊

### ISSUE THREAD

**Issue by luoxuye** [wes-lin/Cloud189Checkin#5]

**Comment by wes-lin** [comment]
已经更新，sync代码即可

**Comment by luoxuye** [comment]
谢谢，能用了，虽然js完全看不懂没办法自己写推送，要是python就好了。

**Comment by wes-lin** [comment]
推送功能后面有空再考虑集成，github还有很多是用python写的版本，我最开始的版本也是参考python写的，如果你会python，再看看js也很快就能上手的。

**Comment by tpGit2022** [comment]
@wes-lin 您好 想问下这些请求流程是分析Android端App得来的吗？ 天翼网盘的App有没有加壳？

**Comment by wes-lin** [comment]
请求是根据web 端的请求分析出来

**Comment by ip520011** [comment]
python版本新鲜出炉：https://github.com/ip520011/Cloud189Checkin/

**Comment by luoxuye** [comment]
> python版本新鲜出炉：https://github.com/ip520011/Cloud189Checkin/

感谢大佬，改了一下可以在action上运行了
