### ISSUE TITLE
nodejs又不行了

### ISSUE THREAD

**Issue by echs-top** [wes-lin/Cloud189Checkin#69]
从7号开始签到失败，今天一看nodejs版本问题
build-and-deploy
The following actions uses Node.js version which is deprecated and will be forced to run on node20: nick-fields/retry@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by wes-lin** [comment]
好的，明天看下

**Comment by wes-lin** [comment]
改了依赖版本,再观察看看,我是都一直成功的

**Comment by TomyJan** [comment]
我这边啥也没动，也是秒失败
<img width="231" alt="image" src="https://github.com/user-attachments/assets/7cdabbfa-a8f3-4159-acd4-1f0f93749fac">

**Comment by wes-lin** [comment]
请留一下最新的readme 我已经更改了账号环境变量
