### ISSUE TITLE
这是哪里有问题

### ISSUE THREAD

**Issue by yc001214** [wes-lin/Cloud189Checkin#72]
Run nick-fields/retry@v3

> cloud@[1](https://github.com/yc001214/Cloud189Checkin/actions/runs/10332876847/job/28604605880#step:6:1).0.0 start
> node --env-file=.env --unhandled-rejections=strict ./src/app.js

Command completed after 1 attempt(s).
![微信截图_20240811001310](https://github.com/user-attachments/assets/9fe63cb9-014b-4f7b-9475-42b6aaaa42c2)

**Comment by wes-lin** [comment]
账号变量没配好，看最新的readme说明

**Comment by yc001214** [comment]
![微信截图_20240811185209](https://github.com/user-attachments/assets/b25266f6-a950-4c49-a0ce-3c5d271d2e27)

**Comment by yc001214** [comment]
> 账号变量没配好，看最新的readme说明TY_ACCOUNTS

不是这样配置吗

**Comment by yc001214** [comment]
![Uploading 微信截图_20240811185209.png…]()

**Comment by yc001214** [comment]
![微信截图_20240811185209](https://github.com/user-attachments/assets/6d2697b7-4949-4398-b81a-e96130a29477)
