### ISSUE TITLE
怎么运行错误

### ISSUE THREAD

**Issue by 1304756868** [wes-lin/Cloud189Checkin#77]
![Screenshot_20240816_203501_Chrome](https://github.com/user-attachments/assets/23134489-39bb-4967-8996-c046a7533737)

**Comment by wes-lin** [comment]
应该是serve酱的推送挂了，建议换push

**Comment by 1304756868** [comment]
![Screenshot_20240817_003315_Telegram](https://github.com/user-attachments/assets/14484379-2f6e-46ad-b638-6fb7059ff02f)

**Comment by 1304756868** [comment]
不显示详细内容了

**Comment by wes-lin** [comment]
看图片不是挺正常的？

**Comment by 1304756868** [comment]
![Screenshot_20240817_172150_Cloud189](https://github.com/user-attachments/assets/a84ae8cd-51ea-4855-a060-098321abfdbc)
看着成功运行了，实际没有

**Comment by 1304756868** [comment]
> 我的也没了。。。。无效了
> 
> ![image](https://private-user-images.githubusercontent.com/83129369/358853214-f6df1c8d-5dac-4b20-a97d-10df6d6d17ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODEyOTQsIm5iZiI6MTcyMzk4MDk5NCwicGF0aCI6Ii84MzEyOTM2OS8zNTg4NTMyMTQtZjZkZjFjOGQtNWRhYy00YjIwLWE5N2QtMTBkZjZkNmQxN2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDExMzYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MjVkMGU5ODU3MTJiNGNjNTIzM2VjY2ViNTc2ZGIzYjNmZDY3YzEwNjcxZjAzYTc2NDI2MTYwZjc2N2ExMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fv5yKRHMcYVUtXalRmol-AGoaQHYVHKfS04xdfueDAI)

账号密码填写方式改变了

**Comment by wes-lin** [comment]
> ![Screenshot_20240817_003315_Telegram](https://private-user-images.githubusercontent.com/23548300/358650428-14484379-2f6e-46ad-b638-6fb7059ff02f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwNDE3MTIsIm5iZiI6MTcyNDA0MTQxMiwicGF0aCI6Ii8yMzU0ODMwMC8zNTg2NTA0MjgtMTQ0ODQzNzktMmY2ZS00NmFkLWI2MzgtNmZiNzA1OWZmMDJmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDA0MjMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNGNlOWQwODE4M2UwODBiNDBmY2Q5YzMzODY5NWQ3Y2MwYmEyZTE4N2JkZWMzMjc2NWFjYzlmMGZkYjhlNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10B54cWk3pQLiAy8DAA9y61xoej9fH4ca4jgVqJqyQI)

参考readme重新配置下
