### ISSUE TITLE
建议出错的，重新添加一次即可

### ISSUE THREAD

**Issue by matocool** [wes-lin/Cloud189Checkin#78]
我之前也是报错，，好多天没运行了。。。

今天上来一看代码更新了。。。

直接删掉FORK的，，，重新FORK一次。。。。第一次运行失败，第二次成功。。。。。

非常感谢大佬

但是第三次抽奖，流程上看得到是成功。。。。。。但是从记录页面并没有。。。不知道到底是啥问题。。

https://github.com/matocool/Cloud189Checkin/actions/runs/10433314686/job/28894906004

![UF44B}CSLS$148`@Q4%{ BT](https://github.com/user-attachments/assets/4091a0d3-a587-49ea-b696-3be5f00ddbc8)

https://cloud.189.cn/web/main/growthRecord

![B4YR@CUOF1BINRIB4`H$% 0](https://github.com/user-attachments/assets/adab702c-65ea-4b3f-aaa8-1ee5001187fc)

**Comment by wes-lin** [comment]
去除无用三次抽奖
