### ISSUE TITLE
大佬 怎么把结果推送到bark

### ISSUE THREAD

**Issue by iowong** [wes-lin/Cloud189Checkin#8]
bark 接收推送只需要一个get请求 求个方法

**Comment by wes-lin** [comment]
还没集成推送功能，这个bark我没用过，可以提供下具体的api文档吗，我可以考虑集成进去

**Comment by iowong** [comment]
> 还没集成推送功能，这个bark我没用过，可以提供下具体的API文档吗，我可以考虑集成进去

https://github.com/Finb/Bark

**Comment by wes-lin** [comment]
已支持server酱推送,可参考server酱配置bark,或者采用其他客户端接.
