### ISSUE TITLE
sendkey已获取，然后如何配置

### ISSUE THREAD

**Issue by djgao234** [wes-lin/Cloud189Checkin#85]
sendkey如何配置到运行的项目里

**Comment by wes-lin** [comment]
查看readme说明

**Comment by djgao234** [comment]
这里面咋输

**Comment by djgao234** [comment]
添加环境中，添加SENDKEY的环境，然后点add enviroment secret之后就不会了
Name和Value要用什么格式填

**Comment by djgao234** [comment]
Value是直接填key吗，还是在项目配置文件里编辑修改

**Comment by djgao234** [comment]
我在.env文件中sendkey=后面添加API key了,是不是就不需要添加SENDKEY环境了
（我是在Fork里部署的）

**Comment by djgao234** [comment]
![image](https://github.com/user-attachments/assets/f3036d11-6d2d-44fb-bbc4-719938b8af85)如图

**Comment by wes-lin** [comment]
> ![image](https://private-user-images.githubusercontent.com/148452992/365538673-f3036d11-6d2d-44fb-bbc4-719938b8af85.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NDM3NTQsIm5iZiI6MTcyNTk0MzQ1NCwicGF0aCI6Ii8xNDg0NTI5OTIvMzY1NTM4NjczLWYzMDM2ZDExLTZkMmQtNDRmYi1iYmM0LTcxOTkzOGI4YWY4NS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMDQ0NDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDliNmU3MTMzMmFjNWE4MmQxNWUzZTQwNGM5YzU3Y2E2ZDhkOTk1MWYyNmZkOWVlMGRiMWQ5ODQ3MDBhNGZlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6Hb5q_cKrvGXE2RLZhMSphwlHzDscvbARiSbjDA5ZBs)如图

name 为SENDKEY value为你的拿到的API KEY,不建议在github上直接改.env会讲你的KEY 暴力出去. 改env比较适用于本地运行

**Comment by djgao234** [comment]
好的
