### ISSUE TITLE
telegram_bot推送增加代理设置

### ISSUE THREAD

**Issue by Merhsia** [wes-lin/Cloud189Checkin#87]
GitHub Action运行已无问题。
本地运行：由于本地服务器没开全局代理，本地运行时使用telegrambot推送消息需要挂proxy代理，希望可以增加代理设置。

**Comment by wes-lin** [comment]
> GitHub Action运行已无问题。
> 本地运行：由于本地服务器没开全局代理，本地运行时使用telegrambot推送消息需要挂proxy代理，希望可以增加代理设置。

有时间会考虑下，但是国内的网络环境，还是建议用别的推送工具。如果想用电报的推送还是配合github action比较好。
