### ISSUE TITLE
希望添加网络重传机制

### ISSUE THREAD

**Issue by LanYunDev** [wes-lin/Cloud189Checkin#89]
在网络不稳定(丢包)环境中,希望能对网络请求失败添加重试机制.
参考日志如下:
[ERROR] default - HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/xxx/Cloud189Checkin/node_modules/got/dist/source/as-promise/index.js:117:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  code: undefined,
  timings: {
    start: 1730170146592,
    socket: 1730170146592,
    lookup: 1730170146592,
    connect: 1730170146592,
    secureConnect: 1730170146592,
    upload: 1730170146593,
    response: 1730170146638,
    end: 1730170146640,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 0,
      tcp: 0,
      tls: 0,
      request: 1,
      firstByte: 45,
      download: 2,
      total: 48
    }
  }
}

**Comment by wes-lin** [comment]
你是在什么环境中运行的？github还是本地。github环境的话是有错误重试

**Comment by LanYunDev** [comment]
本地
