### ISSUE TITLE
这是什么原因？隔几天出现！

### ISSUE THREAD

**Issue by bilibili2077** [wes-lin/Cloud189Checkin#91]
每次隔几天都出现失败的情况，时间间隔还不一样，有时3天有时一个星期，不固定，失败后必须把fork项目同步一下才可以，但是项目看日期是没更新过的，怎么又需要同步呢？而且每次同步都会显示丢弃很多分支，同步完就正常了，会提示签到成功，隔三差五失败后需要手动同步，不知道什么原因！
![屏幕截图 2024-11-10 120752](https://github.com/user-attachments/assets/64430af0-6e05-4058-a91f-62ac202da307)
![屏幕截图 2024-11-10 120819](https://github.com/user-attachments/assets/9271361a-b7c4-437a-9e04-949255e43c32)
![屏幕截图 2024-11-10 121305](https://github.com/user-attachments/assets/1f36c6cb-ce53-4ce7-96fe-260b90af9d14)
![屏幕截图 2024-11-10 121439](https://github.com/user-attachments/assets/2034926b-dcf9-429a-a60f-e0fabe1763a7)

**Comment by wes-lin** [comment]
没人反馈过这种情况，我自己也没遇到。你的log也不够详细，没法帮你判断。

**Comment by bilibili2077** [comment]
> 没人反馈过这种情况，我自己也没遇到。你的log也不够详细，没法帮你判断。

![屏幕截图 2024-11-10 185335](https://github.com/user-attachments/assets/a4d6e812-1be9-47f8-81b7-246cd3dd5374)
![屏幕截图 2024-11-10 185554](https://github.com/user-attachments/assets/9f654f60-3b2c-47ae-afad-d81b25a5ffec)
![屏幕截图 2024-11-10 185609](https://github.com/user-attachments/assets/5608657a-074c-4a04-b347-a656bb4189c7)
![屏幕截图 2024-11-10 185628](https://github.com/user-attachments/assets/f7a03d7c-45ba-4f6c-bb6b-8b8d6cb5893e)
![屏幕截图 2024-11-10 185642](https://github.com/user-attachments/assets/64184b20-c77c-463c-bd3d-f4d4ef2cd40a)

**Comment by bilibili2077** [comment]
> > 没人反馈过这种情况，我自己也没遇到。你的log也不够详细，没法帮你判断。
> 
> ![屏幕截图 2024-11-10 185335](https://private-user-images.githubusercontent.com/95119149/384682337-a4d6e812-1be9-47f8-81b7-246cd3dd5374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzY2NzUsIm5iZiI6MTczMTIzNjM3NSwicGF0aCI6Ii85NTExOTE0OS8zODQ2ODIzMzctYTRkNmU4MTItMWJlOS00N2Y4LTgxYjctMjQ2Y2QzZGQ1Mzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEwNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNGFmZWY1OGVlMTVjYzQ5N2E2OTJiZTdkOGMzMTkzZWI2Y2E4MDkwYjQwYmM0MWUxYWY0NWRiOWQxOWFiMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QsPUG2gHoK5BNpIHCp5Qu-I87exWPwT4NCGADiaUYuQ) ![屏幕截图 2024-11-10 185554](https://private-user-images.githubusercontent.com/95119149/384682341-9f654f60-3b2c-47ae-afad-d81b25a5ffec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzY2NzUsIm5iZiI6MTczMTIzNjM3NSwicGF0aCI6Ii85NTExOTE0OS8zODQ2ODIzNDEtOWY2NTRmNjAtM2IyYy00N2FlLWFmYWQtZDgxYjI1YTVmZmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEwNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YzQ2MzRiZTBmZmM1MzY5YTNmODlhZTY4YjIzN2E1ZDZmOTMxYTUxODcxY2I1YTdjY2M0NjFmNzZhMDIyOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WoN8wAggL7KWN1NIwXm2JbcYHOz8pC6RVMoEpM0iSjk) ![屏幕截图 2024-11-10 185609](https://private-user-images.githubusercontent.com/95119149/384682342-5608657a-074c-4a04-b347-a656bb4189c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzY2NzUsIm5iZiI6MTczMTIzNjM3NSwicGF0aCI6Ii85NTExOTE0OS8zODQ2ODIzNDItNTYwODY1N2EtMDc0Yy00YTA0LWIzNDctYTY1NmJiNDE4OWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEwNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwY2ZkZmQ3OTA3MWI3N2I1MTVlMGI0MjU3MTAzZDcxMGI4NDQzOWQ4YjI1YTA3NTE0OTNiYTEzYzJlNGQwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dWN_QrEkYmjGWGE9EJr9Gi4NFRFaTwvHk--p0B3Cu5Q) ![屏幕截图 2024-11-10 185628](https://private-user-images.githubusercontent.com/95119149/384682343-f7a03d7c-45ba-4f6c-bb6b-8b8d6cb5893e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzY2NzUsIm5iZiI6MTczMTIzNjM3NSwicGF0aCI6Ii85NTExOTE0OS8zODQ2ODIzNDMtZjdhMDNkN2MtNDViYS00ZjZjLWJiNmItOGI4ZDZjYjU4OTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEwNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MGQwMzdjYmJlZmIyYTdhODZkOTc2YTcyZjc3MmUwZGNkNjZmZTA3MDY2ZmExNGVlYzBjMDJiYmQ0MDcyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.K6W05_j9WQTbQnjbPg3lvhGSIN8OKrwZXTk_0uorDMs) ![屏幕截图 2024-11-10 185642](https://private-user-images.githubusercontent.com/95119149/384682344-64184b20-c77c-463c-bd3d-f4d4ef2cd40a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMzY2NzUsIm5iZiI6MTczMTIzNjM3NSwicGF0aCI6Ii85NTExOTE0OS8zODQ2ODIzNDQtNjQxODRiMjAtYzc3Yy00NjNjLWJkM2QtZjRkNGVmMmNkNDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDEwNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyOTE1NTRhYmIwN2ZjOWYwY2E3MjkzOWJmMGU5NjhmNTA1NDk0OThiODY5NzNiYWFjNzUyYjRiYjk1ZjcwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dg6nYTzDGYz3pSa4IytMW9wzwT9FVDFQ7kvNoQnmpGo)

这些是显示错误的地方!

**Comment by wes-lin** [comment]
> > > 没人反馈过这种情况，我自己也没遇到。你的log也不够详细，没法帮你判断。
> 
> 这些是显示错误的地方!
有参考readme配置工作流权限吗?

**Comment by Player-Admin** [comment]
我也遇到这个情况

**Comment by Player-Admin** [comment]
我也遇到这个情况

**Comment by bilibili2077** [comment]
我现在改用dev分支复刻后就没出现过失败了！

**Comment by wes-lin** [comment]
目前dev和master分支代码是一致。还是建议用master试试，dev是平时我用于开发新功能的分支，不建议使用。
