### ISSUE TITLE
图形验证码错误

### ISSUE THREAD

**Issue by zhangyi0112** [wes-lin/Cloud189Checkin#96]
账户 180********开始执行
图形验证码错误，请重新输入
账户 180********执行完毕

-----------
今天增加了验证码了么？

**Comment by wes-lin** [comment]
> 账户 180********开始执行
> 图形验证码错误，请重新输入
> 账户 180********执行完毕
> 
> -----------
> 今天增加了验证码了么？

是否是第一次运行脚本？
